Support PingFederate 11.3.x and fill out support for all PF 11.2.x versions
pingidentity/terraform-provider-pingfederate pull request #149
Opened 2023-12-20 18:02 UTC by henryrecker-pingidentity

- Added new required `product_version` attribute to provider configuration
- Added support for all PF 11.2.x and 11.3.x versions
- Updated descriptions to match latest 11.3.4 spec

2023-12-20 20:50 UTC, PingDavidR approved these changes

2024-01-03 16:27 UTC, wesleymccollam requested changes

2024-01-03 16:27 UTC, wesleymccollam commented on .github/workflows/scheduled-acctests.yaml
> +          # The 11.3.4-latest image isn't out yet, so using 11.3.3 here
11.3.4 is now released

2024-01-03 18:20 UTC, wesleymccollam requested changes

2024-01-03 18:28 UTC, henryrecker-pingidentity commented on internal/resource/config/datastore/data_store_resource.go
> +	compare, err := version.Compare(r.providerConfig.ProductVersion, version.PingFederate1130)
What do you mean specifically? This is all I can imagine reducing it to:
`
pfVersionAtLeastX, err := newCommonVersionAtLeastMethod(r.providerConfig.ProductVersion, version.PingFederateX, &resp.Diagnostics)
if err != nil {
  return
}
`

2024-01-03 19:55 UTC, wesleymccollam commented on internal/resource/config/datastore/data_store_resource.go
> +	compare, err := version.Compare(r.providerConfig.ProductVersion, version.PingFederate1130)
gotcha. Just saw it was repeatable. I guess it doesn't make sense in this scenario.

2024-01-03 19:57 UTC, wesleymccollam approved these changes

2024-01-03 20:05 UTC, henryrecker-pingidentity commented on internal/resource/config/datastore/data_store_resource.go
> +	compare, err := version.Compare(r.providerConfig.ProductVersion, version.PingFederate1130)
Yeah, it is a little repetitive but with Go error handling it's hard to reduce this down very much since we always need the error check.

2024-01-03 20:06 UTC, merged